global:
  scrape_interval: 5s

scrape_configs:
  - job_name: 'kafka_push'
    static_configs:
      - targets: ['random_generator:9101']
  - job_name: 'kafka_consumer'
    static_configs:
      - targets: ['kafka_consumer:9102']
  - job_name: 'mongo_to_postgres'
    static_configs:
      - targets: ['mongo_to_postgres:9103'] 